name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
      - 3.4.x
      - 3.3.x
      - 3.2.x

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12.12, 2.11.12]
    container:
      image: ucbbar/chisel3-tools
      options: --user github --entrypoint /bin/bash
    env:
      CONTAINER_HOME: /home/github

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Documentation (Scala 2.12 only)
        if: matrix.scala == '2.12.12'
        run: sbt ++${{ matrix.scala }} docs/mdoc
      - name: Test
        run: sbt ++${{ matrix.scala }} test
      - name: Binary compatibility
        run: sbt ++${{ matrix.scala }} mimaReportBinaryIssues
      # Publishing steps
      # These steps are here to avoid duplicated work and logic
      - name: Setup GPG (for Publish)
        id: publish_start
        # on.push.branches above enforces we only publish from correct branches
        # TODO Uncomment below line before merging
        # if: github.event_name == 'push'
        uses: olafurpg/setup-gpg@v3
      - name: Publish
        # publish_start if guards this step
        if: steps.publish_start.outcome != 'skipped'
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}


  # Sentinel job to simplify how we specify which checks need to pass in branch
  # protection and in Mergify
  #
  # When adding new jobs, please add them to `needs` below
  all_tests_passed:
    name: "all tests passed"
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success!
